### ISSUE TITLE
Swift support for scopes

### ISSUE THREAD

**Issue by abury** [shyambhat/InstagramKit#152]
Hey @shyambhat 

Having an issue getting an AuthURL for multiple scopes. The example shown in the README shows how to use C style enums in Objective-C but Swift doesn't allow the | operator to swift style enums.

Any thoughts on this? (Or a recommended workaround?) 

Thanks

**Comment by manumax** [comment]
I took a quick look at the code and I discovered that `InstagramKitLoginScope` is declared using `NS_ENUM` instead of `NS_OPTIONS`. I haven't had the time to try out the following but I would suggest you to change the declaration of `InstagramKitLoginScope` from `NS_ENUM` to `NS_OPTIONS` and rebuild your project (you'll find the declaration in`InstagramKitConstants.h`). In this way `InstagramKitLoginScope` will properly 'converted' to a `OptionSetType` instead of a `enum` type. 

Then you should be able to write something like:

```swift
let scope: InstagramKitLoginScope = [InstagramKitLoginScope.Basic, InstagramKitLoginScope.Comments]
let authURL = InstagramEngine.sharedEngine().authorizarionURLForScope(scope)
self.webView?.loadRequest(NSURLRequest(URL: authURL))
```

If all works fine, I would suggest you to submit a PR.

**Comment by abury** [comment]
Thanks @manumax! I'll do just that :smiley:

**Comment by shyambhat** [comment]
Thanks guys. I'm still getting my way around supporting swift seamlessly. Any contributions would be huge help. Cheers!
